name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Kubeconfig for Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Pull Docker image
        run: docker pull your-docker-repository/your-app:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Update service
        run: kubectl rollout restart deployment/your-app-deployment